### ISSUE TITLE
MS_plot calling mis-documentation

### ISSUE THREAD

**Issue by savagema** [andreww/MSAT#31]
Thanks for a great program! However, one always wants more...

I think there is a problem with the documentation for MS_plot when plotting one's own data, in terms of the forms of the matrices/vectors called. The document for how to plot your own observations on the stereonets for MS_plot says this:

   

>  MS_plot(..., 'sdata', azimuth, inclination, polarisation, avs)
>            Add data points to the P-wave velocity ('VP') or S-wave 
>            polarisation plot ('AVSPOL'), respectively. This can be used,
>            for example, to compare an elastic model with shear-wave
>            splitting measurements. In each case data points relate
>            to a ray propagating in a direction described by the azimuth 
>            and inclination. The point is coloured according to either 
>            the P-wave velocity, vp, or S-wave anisotropy, avs, in km/s
>            or %. In the case of S-wave anisotropy, the fast polarisation 
>            direction is also shown. _**Each argument (azimuth, inclination, 
>            vp, polarisation and avs) is an array and each must be the 
>            same length.**_

However, the program bombs if they are all the same 1xn or nx1 dimensions.  I found I needed to make the variables azimuth and inclination have the same dimensions, but polarisation and avs need to be the transpose, i.e. if azimuth and inclination are each 1xn, then polarisation and avs need to be nx1.

**Comment by andreww** [comment]
Thanks for the report. I'm struggling to reproduce the this here (using Matlab R2013a). The following (with everything size 1x3) runs without an error:

    [C, r] = MS_elasticDB('ol')
    azi_dat = [30 60 90]
    inc_dat = [30 60 90]
    pol_dat = [90 90 90]
    avs_dat = [1.0 2.0 3.0]
    MS_plot(C, r, 'sdata', azi_dat, inc_dat, pol_dat, avs_dat)

if I transpose anything I end up with an error. Do we just say that each argument must be a scalar or a 1xn array (check for this to give a nicer error message in the code)?

**Comment by savagema** [comment]
Hi Andrew,  thanks for that.  I actually discovered that part of my problem was misunderstanding the matlab prime symbol in the context of a command I had copied from one of the example scripts.  However, the documentation is still slightly wrong in that the variables need to be all 1xn (horizontal) dimensions. I get an error if I try to transpose them all., i.e., if they are all n x 1 (vertical)

**Comment by andreww** [comment]
Fixes for this are sat on the "ms_plot_enhance" branch (see #33) along with the ability to do equal angle and equal area projections and to swap between upper and lower hemisphere plots. I ended up allowing any shape of input for sdata and pdata - the number of elements in each argument just need to agree.

This will end up in the next formal release, and in the development version much more quickly.

**Comment by savagema** [comment]
Great, thanks!

Martha Savage
Professor of Geophysics
SGEES
Victoria University of Wellington
Te Whare Wananga o te Upoko o te Ika a Maui
Cotton 529
Box 600, Wellington 6140
New Zealand

Email: Martha.Savage@vuw.ac.nz<mailto:Martha.Savage@vuw.ac.nz>
DDI: +64 (0)4 463-5961
Mobile: +64 (0)21-262-7516
